### ISSUE TITLE
Not work with programmatically created view

### ISSUE THREAD

**Issue by breakind** [dagronf/DSFInspectorPanes#1]
let customView = NSView(frame: NSRect(x: 0, y: 0, width: 200, height: 200))
        self.panes.addPane(
            title: "Custom View",
            view: customView
        )

It would show up like this：
![1670223732807](https://user-images.githubusercontent.com/2801515/205571221-9b1d0cff-dcb9-4405-b9ff-5fc2b374663d.jpg)

did i use it wrong?

**Comment by dagronf** [comment]
Hi there! Sorry to see you’re having issues.

Most likely the problem is related to autolayout constraints - the view you’re adding has none, so the size of the view ends up being 0.

can you try adding a width and height constraint to the view and see if the view appears?

**Comment by breakind** [comment]
let customView = NSView(frame: NSRect(x: 0, y: 0, width: 200, height: 200))
customView.widthAnchor.constraint(equalToConstant: 200).isActive = true
customView.heightAnchor.constraint(equalToConstant: 200).isActive = true

It's work now！
Thanks so much for sharing this cool code and your prompt reply!
