### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by DevulderJeanPaul** [dagronf/DSFInspectorPanes#2]
Show or hide a pane

var propertyPanes = DSFInspectorPanesView()
…
propertyPanes.panes[0].hide = true
propertyPanes.panes[1].hide = false

Property hide are removed ???

Thanks,

**Comment by dagronf** [comment]
Hi @DevulderJeanPaul, documentation has been updated to correct the error

`hide` is now `isHidden` (which is in line with the standard Apple APIs)
`expanded` is now `isExpanded` (same as above)

I've upped the version to v2.0.0 (as its a breaking API change, even if it's a small change). Please let me know if you have any issue with these changes!

**Comment by DevulderJeanPaul** [comment]
Hi,
It's Ok
Thanks,
